---
- name: Install tripwire on enterprise linux
  hosts: Greg-rocky9
  gather_facts: false
  become: yes
  vars:
    # The following should be supplied at run time securely
    site_key: Site key contents
    site_key_password: Password for site key
    local_key_password: Password for local key

  tasks:
    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install tripwire
      ansible.builtin.dnf:
        name: tripwire
        state: present

    - name: Install the tripwire site key from the contents of the site_key variable
      ansible.builtin.copy:
        content: "{{ site_key }}"
        dest: /etc/tripwire/site.key
        owner: root
        group: root
        mode: 0600
      no_log: true

    # - name: Generate the local key based on hostname
    #   # ansible.builtin.shell: /usr/sbin/tripwire --init -P local.key -L /var/lib/tripwire/$(hostname)-local.key -Q $(echo "{{ local_key_password }}" | sha256sum | awk '{print $1}')
    #   # ansible.builtin.shell: "twadmin --generate-keys -L /etc/tripwire/${HOSTNAME}-local.key -Q {{ local_key_password }}"
    #   ansible.builtin.shell: "twadmin --generate-keys -L /etc/tripwire/{{ inventory_hostname }}-local.key" # -Q {{ local_key_password }}"

# Enter the local keyfile passphrase:
# Verify the local keyfile passphrase:
    - name: Use expect to generate local key based on hostname
      ansible.builtin.expect:
        command: twadmin --generate-keys -L /etc/tripwire/{{ inventory_hostname }}-local.key
        responses:
          Enter the local keyfile passphrase: "{{ local_key_password }}"
          Verify the local keyfile passphrase: "{{ local_key_password }}"