---
- name: Install tripwire on enterprise linux
  hosts: Greg-rocky9
  gather_facts: false
  become: yes
  vars:
    # The following should be supplied at run time securely
    site_key: Site key contents
    site_key_password: Password for site key
    local_key_password: Password for local key

  tasks:
    - name: Use the tripwire role to install tripwire
      include_role:
        name: tripwire
      tags:
        - full-install