---
- name: Install tripwire on enterprise linux
  hosts: Greg-rocky9
  gather_facts: false
  become: yes
  vars:
    # The following should be supplied at run time securely
    site_key: Site key contents
    site_key_password: Password for site key
    local_key_password: Password for local key

  tasks:
    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install tripwire
      ansible.builtin.dnf:
        name: tripwire
        state: present

    - name: Install pexpect Python package on the remote host
      ansible.builtin.pip:
        name: pexpect

    - name: Use expect to generate local key based on hostname
      ansible.builtin.expect:
        command: twadmin --generate-keys -L /etc/tripwire/{{ inventory_hostname }}-local.key
        responses:
          Enter the local keyfile passphrase: "{{ local_key_password }}"
          Verify the local keyfile passphrase: "{{ local_key_password }}"

    - name: Use expect to generate site key
      ansible.builtin.expect:
        command: twadmin --generate-keys -S /etc/tripwire/site.key
        responses:
          Enter the site keyfile passphrase: "{{ site_key_password }}"
          Verify the site keyfile passphrase: "{{ site_key_password }}"

    - name: Change MAILNOVIOLATIONS to false in /etc/tripwire/twcfg.txt
      ansible.builtin.lineinfile:
        path: /etc/tripwire/twcfg.txt
        regexp: '^MAILNOVIOLATIONS\s*=\s*true'
        line: 'MAILNOVIOLATIONS       =false'

    - name: Ignore root folder ansible tmp files
      ansible.builtin.lineinfile:
        path: /etc/tripwire/twpol.txt
        line: "     !/root/.ansible/tmp ;"
        insertbefore: "^.*Catch all additions to /root"
        state: present  # Ensures the line is only added if it doesn’t already exist

    - name: Use expect to generate config file
      ansible.builtin.expect:
        command: twadmin --create-cfgfile -S /etc/tripwire/site.key /etc/tripwire/twcfg.txt
        responses:
          Please enter your site passphrase: "{{ site_key_password }}"

    - name: Use expect to generate policy file
      ansible.builtin.expect:
        command: twadmin --create-polfile -S /etc/tripwire/site.key /etc/tripwire/twpol.txt
        responses:
          Please enter your site passphrase: "{{ site_key_password }}"

    - name: Use expect to run tripwire init
      ansible.builtin.expect:
        command: tripwire --init
        responses:
          Please enter your local passphrase: "{{ local_key_password }}"
        timeout: 300

    - name: Run a tripwire check
      ansible.builtin.command: tripwire --check
      register: tripwire_check
      failed_when: '"Integrity check complete." not in tripwire_check.stdout'

    - name: Extract the file path from command output
      set_fact:
        # report_file_path: "{{ tripwire_check | regex_search('Wrote report file: (\\/.*\\.twr)', '\\1') }}"
        report_file_path: "{{ tripwire_check.stdout.split('\n') | select('search', 'Wrote report file:') | first | regex_search('Wrote report file: (\\/.*\\.twr)', '\\1') }}"

    - name: Use expect to run the tripwire database --update
      ansible.builtin.expect:
        command: tripwire --update --accept-all -r "{{ report_file_path[0] }}"
        responses:
          Please enter your local passphrase: "{{ local_key_password }}"
        timeout: 300