---
- name: Change MAILNOVIOLATIONS to false in /etc/tripwire/twcfg.txt
  ansible.builtin.lineinfile:
    path: /etc/tripwire/twcfg.txt
    regexp: '^MAILNOVIOLATIONS\s*=\s*true'
    line: 'MAILNOVIOLATIONS       =false'

- name: Use expect to generate config file
  ansible.builtin.expect:
    command: twadmin --create-cfgfile -S /etc/tripwire/site.key /etc/tripwire/twcfg.txt
    responses:
      Please enter your site passphrase: "{{ site_key_password }}"

