---
- name: Ignore root folder ansible tmp files
  ansible.builtin.lineinfile:
    path: /etc/tripwire/twpol.txt
    line: "     !/root/.ansible/tmp ;"
    insertbefore: "^.*Catch all additions to /root"
    state: present  # Ensures the line is only added if it doesn’t already exist

- name: Use expect to generate policy file
  ansible.builtin.expect:
    command: twadmin --create-polfile -S /etc/tripwire/site.key /etc/tripwire/twpol.txt
    responses:
      Please enter your site passphrase: "{{ site_key_password }}"
  no_log: true